const HR_V2_QUESTIONS = [
  {
    key: 'hr_work_days',
    prompt: 'Which days does your company work?',
    type: 'multi_choice',
    options: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    required: true,
    section: 'HR Setup',
    question_number: 1,
    sdf_mapping: { target: 'modules.hr.work_days' },
    sdf_impact_notes: 'Sets modules.hr.work_days array. Forwarded into leave_engine, leave_approvals, and attendance_time sub-pack configs for working-day calculations.',
    order_index: 0,
  },
  {
    key: 'hr_daily_hours',
    prompt: 'How many hours is a normal work day?',
    type: 'choice',
    options: ['6', '7', '8', '9', '10'],
    allow_custom: true,
    required: true,
    section: 'HR Setup',
    question_number: 2,
    sdf_mapping: { target: 'modules.hr.daily_hours' },
    sdf_impact_notes: 'Sets modules.hr.daily_hours number. Forwarded into leave_engine, leave_approvals, and attendance_time sub-pack configs for overtime split calculations.',
    order_index: 1,
  },
  {
    key: 'hr_enable_leave_engine',
    prompt: 'Do you want to track how many leave days each employee has remaining?',
    type: 'yes_no',
    required: true,
    section: 'HR Capabilities',
    question_number: 3,
    sdf_mapping: { target: 'modules.hr.leave_engine.enabled' },
    sdf_impact_notes: 'Enables modules.hr.leave_engine with entity refs (leave_entity, balance_entity). Creates leaves entity (employee_id, leave_type, start_date, end_date, leave_days, status [Pending/Approved/Rejected/Cancelled], approver_id, approved_at, rejected_at, cancelled_at, rejection_reason, decision_key). Creates leave_balances entity (employee_id, leave_type, year, annual_entitlement, accrued_days, consumed_days, carry_forward_days, available_days, last_accrual_at, note).',
    order_index: 2,
  },
  {
    key: 'hr_enable_leave_approvals',
    prompt: 'Do leave requests need to be approved before the employee can take time off?',
    type: 'yes_no',
    required: true,
    section: 'HR Capabilities',
    question_number: 4,
    sdf_mapping: { target: 'modules.hr.leave_approvals.enabled' },
    sdf_impact_notes: 'Enables modules.hr.leave_approvals with enforce_transitions=true and entity refs (leave_entity, balance_entity). Creates leaves entity if not already created by Q3 (same fields). Wires HRLeaveApprovalMixin with approval workflow, status transitions, and balance consumption on approval.',
    order_index: 3,
  },
  {
    key: 'hr_enable_attendance_time',
    prompt: 'Do you need to track when employees arrive, leave, and how many hours they worked?',
    type: 'yes_no',
    required: true,
    section: 'HR Capabilities',
    question_number: 5,
    sdf_mapping: { target: 'modules.hr.attendance_time.enabled' },
    sdf_impact_notes: 'Enables modules.hr.attendance_time with entity refs (attendance_entity, shift_entity, timesheet_entity). Creates attendance_entries entity (employee_id, work_date, check_in_at, check_out_at, worked_hours, status [Present/Absent/Half Day/On Leave], note). Creates shift_assignments entity (employee_id, shift_name, start_time, end_time, work_date). Creates timesheet_entries entity (employee_id, work_date, attendance_id, regular_hours, overtime_hours, status [Draft/Approved]).',
    order_index: 4,
  },
  {
    key: 'hr_enable_compensation_ledger',
    prompt: 'Do you want to record salary, allowances, and deductions for payroll preparation?',
    type: 'yes_no',
    required: true,
    section: 'HR Capabilities',
    question_number: 6,
    sdf_mapping: { target: 'modules.hr.compensation_ledger.enabled' },
    sdf_impact_notes: 'Enables modules.hr.compensation_ledger with entity refs (ledger_entity, snapshot_entity). Adds salary field to employees entity. Creates compensation_ledger entity (employee_id, pay_period, component, component_type [Earning/Deduction], amount, status [Draft/Posted/Cancelled], posted_at, post_reference). Creates compensation_snapshots entity (employee_id, pay_period, gross_amount, deduction_amount, net_amount, status [Draft/Posted], posted_at, note).',
    order_index: 5,
  },
  {
    key: 'hr_leave_types',
    prompt: 'What types of leave do your employees use?',
    type: 'multi_choice',
    options: ['Sick Leave', 'Vacation / Annual', 'Unpaid Leave', 'Maternity / Paternity', 'Personal / Family'],
    allow_custom: true,
    required: true,
    section: 'HR Setup',
    question_number: 7,
    sdf_mapping: { target: 'entities.leaves.fields.leave_type.options' },
    sdf_impact_notes: 'Sets the options array on the leave_type field of the leaves entity. Also populates leave_type options on the leave_balances entity for per-type balance tracking.',
    order_index: 6,
  },
];

module.exports = {
  module: 'hr',
  version: 'hr.v2',
  template_type: 'sdf_impact_only',
  getQuestions() {
    return JSON.parse(JSON.stringify(HR_V2_QUESTIONS));
  },
};
