const HR_V1_COMPACT_QUESTIONS = [
  {
    key: 'hr_enable_module',
    prompt: 'Do you want HR in your ERP?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.hr.enabled' },
  },
  {
    key: 'hr_work_days',
    prompt: 'What are your normal working days?',
    type: 'multi_choice',
    options: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.hr.work_days' },
  },
  {
    key: 'hr_daily_hours',
    prompt: 'How many hours is a normal work day?',
    type: 'text',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.hr.daily_hours' },
  },
  {
    key: 'hr_enable_leave_engine_pack',
    prompt: 'Do you want leave balance and accrual tracking?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.hr.leave_engine.enabled' },
  },
  {
    key: 'hr_enable_leave_approvals_pack',
    prompt: 'Do leave requests need approval workflow?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.hr.leave_approvals.enabled' },
  },
  {
    key: 'hr_enable_attendance_time_pack',
    prompt: 'Do you want attendance + shift + timesheet tracking?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.hr.attendance_time.enabled' },
  },
  {
    key: 'hr_enable_compensation_ledger_pack',
    prompt: 'Do you want compensation ledger and payroll snapshots?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.hr.compensation_ledger.enabled' },
  },
  {
    key: 'hr_leave_use_default_status_field',
    prompt: "Use default leave status field name 'status'?",
    type: 'yes_no',
    required: true,
    section: 'Leave Workflow Detail',
    condition: {
      op: 'any',
      rules: [
        { question_key: 'hr_enable_leave_engine_pack', equals: 'yes' },
        { question_key: 'hr_enable_leave_approvals_pack', equals: 'yes' },
      ],
    },
    sdf_mapping: { target: 'modules.hr.leave.status_field_mode' },
  },
  {
    key: 'hr_leave_status_field_name_custom',
    prompt: 'What should we call the leave status field?',
    type: 'text',
    required: true,
    section: 'Leave Workflow Detail',
    condition: {
      op: 'all',
      rules: [{ question_key: 'hr_leave_use_default_status_field', equals: 'no' }],
    },
    sdf_mapping: { target: 'modules.hr.leave.status_field' },
  },
  {
    key: 'hr_leave_approval_strict_transitions',
    prompt: 'Should leave status transitions be strictly enforced?',
    type: 'yes_no',
    required: true,
    section: 'Leave Workflow Detail',
    condition: {
      op: 'all',
      rules: [{ question_key: 'hr_enable_leave_approvals_pack', equals: 'yes' }],
    },
    sdf_mapping: { target: 'modules.hr.leave_approvals.enforce_transitions' },
  },
  {
    key: 'hr_use_default_entity_names',
    prompt:
      'Use default HR record names (employees, departments, leaves, leave_balances, attendance_entries, shift_assignments, timesheet_entries, compensation_ledger, compensation_snapshots)?',
    type: 'yes_no',
    required: true,
    section: 'Naming Questions',
    sdf_mapping: { target: 'modules.hr.use_default_entity_names' },
  },
  {
    key: 'hr_employee_entity_name',
    prompt: 'What should we call employee records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [{ question_key: 'hr_use_default_entity_names', equals: 'no' }],
    },
    sdf_mapping: { target: 'modules.hr.employee_entity' },
  },
  {
    key: 'hr_department_entity_name',
    prompt: 'What should we call department records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [{ question_key: 'hr_use_default_entity_names', equals: 'no' }],
    },
    sdf_mapping: { target: 'modules.hr.department_entity' },
  },
  {
    key: 'hr_leave_entity_name',
    prompt: 'What should we call leave records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [{ question_key: 'hr_use_default_entity_names', equals: 'no' }],
    },
    sdf_mapping: { target: 'modules.hr.leave_entity' },
  },
  {
    key: 'hr_leave_engine_entity_name',
    prompt: 'What should we call leave balance records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'hr_enable_leave_engine_pack', equals: 'yes' },
        { question_key: 'hr_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.hr.leave_engine.balance_entity' },
  },
  {
    key: 'hr_attendance_entity_name',
    prompt: 'What should we call attendance records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'hr_enable_attendance_time_pack', equals: 'yes' },
        { question_key: 'hr_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.hr.attendance_time.attendance_entity' },
  },
  {
    key: 'hr_shift_entity_name',
    prompt: 'What should we call shift assignment records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'hr_enable_attendance_time_pack', equals: 'yes' },
        { question_key: 'hr_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.hr.attendance_time.shift_entity' },
  },
  {
    key: 'hr_timesheet_entity_name',
    prompt: 'What should we call timesheet records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'hr_enable_attendance_time_pack', equals: 'yes' },
        { question_key: 'hr_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.hr.attendance_time.timesheet_entity' },
  },
  {
    key: 'hr_compensation_ledger_entity_name',
    prompt: 'What should we call compensation ledger records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'hr_enable_compensation_ledger_pack', equals: 'yes' },
        { question_key: 'hr_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.hr.compensation_ledger.ledger_entity' },
  },
  {
    key: 'hr_compensation_snapshot_entity_name',
    prompt: 'What should we call compensation snapshot records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'hr_enable_compensation_ledger_pack', equals: 'yes' },
        { question_key: 'hr_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.hr.compensation_ledger.snapshot_entity' },
  },
];

module.exports = {
  module: 'hr',
  version: 'hr.v1',
  template_type: 'sdf_impact_compact',
  source_path: null,
  getQuestions() {
    return HR_V1_COMPACT_QUESTIONS.map((question, index) => ({
      ...question,
      order_index: index,
    }));
  },
};
