const INVOICE_V2_QUESTIONS = [
  {
    key: 'invoice_currency',
    prompt: 'What currency do you use for invoices?',
    type: 'choice',
    options: ['USD', 'EUR', 'GBP', 'TRY', 'AED', 'SAR', 'Other'],
    allow_custom: true,
    required: true,
    section: 'Invoice Setup',
    question_number: 1,
    sdf_mapping: { target: 'modules.invoice.currency' },
    sdf_impact_notes: 'Sets modules.invoice.currency string. Used by InvoiceMixin for header formatting and by frontend for currency display (Intl.NumberFormat).',
    order_index: 0,
  },
  {
    key: 'invoice_tax_rate',
    prompt: 'What is your standard tax rate (%)?',
    type: 'choice',
    options: ['0', '1', '5', '8', '10', '18', '20', 'Custom'],
    allow_custom: true,
    required: true,
    section: 'Invoice Setup',
    question_number: 2,
    sdf_mapping: { target: 'modules.invoice.tax_rate' },
    sdf_impact_notes: 'Sets modules.invoice.tax_rate number. Used by InvoiceMixin and InvoiceItemsMixin for automatic tax_total calculation on invoice header.',
    order_index: 1,
  },
  {
    key: 'invoice_enable_payments',
    prompt: 'Do you want to record payments against invoices and track what is still owed?',
    type: 'yes_no',
    required: true,
    section: 'Invoice Capabilities',
    question_number: 3,
    sdf_mapping: { target: 'modules.invoice.payments.enabled' },
    sdf_impact_notes: 'Enables modules.invoice.payments with entity refs (payment_entity, allocation_entity, invoice_entity). Creates invoice_payments entity (payment_number, invoice_id, amount, payment_date, payment_method, status [Draft/Posted/Cancelled], reference_number, posted_at, cancelled_at, cancel_reason, note). Creates invoice_payment_allocations entity (payment_id, invoice_id, amount). Wires InvoicePaymentWorkflowMixin for payment recording, posting, cancellation.',
    order_index: 2,
  },
  {
    key: 'invoice_enable_notes',
    prompt: 'Do you need credit notes or debit notes to adjust invoices after they are sent?',
    type: 'yes_no',
    required: true,
    section: 'Invoice Capabilities',
    question_number: 4,
    sdf_mapping: { target: 'modules.invoice.notes.enabled' },
    sdf_impact_notes: 'Enables modules.invoice.notes with entity refs (note_entity, invoice_entity). Creates invoice_notes entity (note_number, source_invoice_id, note_type [Credit/Debit], amount, tax_total, grand_total, status [Draft/Posted/Cancelled], issue_date, reason, post_reference, posted_at, cancelled_at, cancel_reason, note). Wires InvoiceNoteWorkflowMixin for credit/debit note creation, posting, and invoice balance impact.',
    order_index: 3,
  },
  {
    key: 'invoice_enable_calc_engine',
    prompt: 'Do you want per-line discounts and extra charges on invoice lines?',
    type: 'yes_no',
    required: true,
    section: 'Invoice Capabilities',
    question_number: 5,
    sdf_mapping: { target: 'modules.invoice.calculation_engine.enabled' },
    sdf_impact_notes: 'Enables modules.invoice.calculation_engine with entity refs (invoice_entity, item_entity). Adds discount_total and additional_charges_total fields to invoices header. Adds line-level fields to invoice_items: line_subtotal, line_discount_type [Percent/Fixed], line_discount_value, line_discount_amount, line_tax_rate, line_tax_amount, line_charges. Wires InvoiceCalculationEngineMixin instead of InvoiceItemsMixin.',
    order_index: 4,
  },
  {
    key: 'invoice_print',
    prompt: 'Do you want to print or download invoices as PDF?',
    type: 'yes_no',
    required: true,
    section: 'Invoice Extras',
    question_number: 6,
    sdf_mapping: { target: 'entities.invoices.features.print_invoice' },
    sdf_impact_notes: 'Sets entities.invoices.features.print_invoice = true. Enables print/download button on the invoice form page in the generated frontend.',
    order_index: 5,
  },
];

module.exports = {
  module: 'invoice',
  version: 'invoice.v2',
  template_type: 'sdf_impact_only',
  getQuestions() {
    return JSON.parse(JSON.stringify(INVOICE_V2_QUESTIONS));
  },
};
