const INVOICE_V1_COMPACT_QUESTIONS = [
  {
    key: 'invoice_enable_module',
    prompt: 'Do you want Invoice in your ERP?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.enabled' },
  },
  {
    key: 'invoice_currency',
    prompt: 'What is your main invoice currency?',
    type: 'choice',
    options: ['USD', 'EUR', 'GBP', 'TRY', 'AED', 'SAR', 'Other'],
    allow_custom: true,
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.currency' },
  },
  {
    key: 'invoice_default_tax_rate',
    prompt: 'What is your default tax rate (%)?',
    type: 'text',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.tax_rate' },
  },
  {
    key: 'invoice_prefix',
    prompt: 'What prefix should invoice numbers start with?',
    type: 'text',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.prefix' },
  },
  {
    key: 'invoice_enable_transactions_pack',
    prompt: 'Enable transaction-safe invoice posting and number allocation?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.transactions.enabled' },
  },
  {
    key: 'invoice_enable_payments_pack',
    prompt: 'Do you want payment tracking and allocation?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.payments.enabled' },
  },
  {
    key: 'invoice_enable_notes_pack',
    prompt: 'Do you want credit/debit note workflows linked to invoices?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.notes.enabled' },
  },
  {
    key: 'invoice_enable_lifecycle_pack',
    prompt: 'Do you want strict invoice status workflow (Draft, Sent, Paid, Overdue, Cancelled)?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.lifecycle.enabled' },
  },
  {
    key: 'invoice_enable_calc_engine_pack',
    prompt: 'Do you want line-level calculations (line discount, tax, additional charges)?',
    type: 'yes_no',
    required: true,
    section: 'Core Questions (Always Ask)',
    sdf_mapping: { target: 'modules.invoice.calculation_engine.enabled' },
  },
  {
    key: 'invoice_enforce_transitions',
    prompt: 'Should status transitions be strictly enforced?',
    type: 'yes_no',
    required: true,
    section: 'Lifecycle Detail',
    condition: {
      op: 'all',
      rules: [{ question_key: 'invoice_enable_lifecycle_pack', equals: 'yes' }],
    },
    sdf_mapping: { target: 'modules.invoice.lifecycle.enforce_transitions' },
  },
  {
    key: 'invoice_lifecycle_use_default_status_field',
    prompt: "Use default status field name 'status'?",
    type: 'yes_no',
    required: true,
    section: 'Lifecycle Detail',
    condition: {
      op: 'all',
      rules: [{ question_key: 'invoice_enable_lifecycle_pack', equals: 'yes' }],
    },
    sdf_mapping: { target: 'modules.invoice.lifecycle.status_field_mode' },
  },
  {
    key: 'invoice_status_field_name_custom',
    prompt: 'What should we call the invoice status field?',
    type: 'text',
    required: true,
    section: 'Lifecycle Detail',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_lifecycle_pack', equals: 'yes' },
        { question_key: 'invoice_lifecycle_use_default_status_field', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.lifecycle.status_field' },
  },
  {
    key: 'invoice_use_default_entity_names',
    prompt: 'Use default names (invoices, invoice_items, invoice_payments, invoice_payment_allocations, invoice_notes)?',
    type: 'yes_no',
    required: true,
    section: 'Naming Questions',
    sdf_mapping: { target: 'modules.invoice.use_default_entity_names' },
  },
  {
    key: 'invoice_entity_name',
    prompt: 'What should we call invoice header records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [{ question_key: 'invoice_use_default_entity_names', equals: 'no' }],
    },
    sdf_mapping: { target: 'modules.invoice.invoice_entity' },
  },
  {
    key: 'invoice_item_entity_name',
    prompt: 'What should we call invoice line item records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [{ question_key: 'invoice_use_default_entity_names', equals: 'no' }],
    },
    sdf_mapping: { target: 'modules.invoice.invoice_item_entity' },
  },
  {
    key: 'invoice_customer_entity_name',
    prompt: 'What should we call customer records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [{ question_key: 'invoice_use_default_entity_names', equals: 'no' }],
    },
    sdf_mapping: { target: 'modules.invoice.customer_entity' },
  },
  {
    key: 'invoice_payment_entity_name',
    prompt: 'What should we call payment records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_payments_pack', equals: 'yes' },
        { question_key: 'invoice_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.payments.payment_entity' },
  },
  {
    key: 'invoice_allocation_entity_name',
    prompt: 'What should we call payment allocation records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_payments_pack', equals: 'yes' },
        { question_key: 'invoice_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.payments.allocation_entity' },
  },
  {
    key: 'invoice_note_entity_name',
    prompt: 'What should we call invoice adjustment note records?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_notes_pack', equals: 'yes' },
        { question_key: 'invoice_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.notes.note_entity' },
  },
  {
    key: 'invoice_use_default_item_field_names',
    prompt: 'Use default invoice line field names (quantity, unit_price, line_tax_total, line_total)?',
    type: 'yes_no',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_calc_engine_pack', equals: 'yes' },
        { question_key: 'invoice_use_default_entity_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.calculation_engine.use_default_item_field_names' },
  },
  {
    key: 'invoice_item_quantity_field_name',
    prompt: 'What should we call the invoice line quantity field?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_calc_engine_pack', equals: 'yes' },
        { question_key: 'invoice_use_default_entity_names', equals: 'no' },
        { question_key: 'invoice_use_default_item_field_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.calculation_engine.item_quantity_field' },
  },
  {
    key: 'invoice_item_unit_price_field_name',
    prompt: 'What should we call the invoice line unit price field?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_calc_engine_pack', equals: 'yes' },
        { question_key: 'invoice_use_default_entity_names', equals: 'no' },
        { question_key: 'invoice_use_default_item_field_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.calculation_engine.item_unit_price_field' },
  },
  {
    key: 'invoice_item_tax_total_field_name',
    prompt: 'What should we call the invoice line tax total field?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_calc_engine_pack', equals: 'yes' },
        { question_key: 'invoice_use_default_entity_names', equals: 'no' },
        { question_key: 'invoice_use_default_item_field_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.calculation_engine.item_tax_total_field' },
  },
  {
    key: 'invoice_item_line_total_field_name',
    prompt: 'What should we call the invoice line total field?',
    type: 'text',
    required: true,
    section: 'Naming Questions',
    condition: {
      op: 'all',
      rules: [
        { question_key: 'invoice_enable_calc_engine_pack', equals: 'yes' },
        { question_key: 'invoice_use_default_entity_names', equals: 'no' },
        { question_key: 'invoice_use_default_item_field_names', equals: 'no' },
      ],
    },
    sdf_mapping: { target: 'modules.invoice.calculation_engine.item_line_total_field' },
  },
];

module.exports = {
  module: 'invoice',
  version: 'invoice.v1',
  template_type: 'sdf_impact_compact',
  source_path: null,
  getQuestions() {
    return INVOICE_V1_COMPACT_QUESTIONS.map((question, index) => ({
      ...question,
      order_index: index,
    }));
  },
};
