// platform/assembler/generators/frontend/statusFormatter.js
//
// Plan D follow-up #7: Generate a `formatStatus(entitySlug, value)` helper for
// the generated frontend so workflow statuses (Pending, Approved, Posted, ...)
// can be displayed in the project's locale instead of leaking raw English
// enum values into a Turkish UI.
//
// The labels dictionary is baked into the emitted file at codegen time using
// the project language pulled from `platform/assembler/i18n/<lang>.json`
// under the `status.<entity>.<value_slug>` key tree. The helper falls back to
// the raw value when no key is present, matching the assembler-side `tFor`.

const { tFor, normalizeLanguage } = require('../../i18n/labels');

// Mirror of sdfLocalizationLint._slugifyValue (kept inline to avoid coupling
// generator code to lint internals).
function slugifyValue(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

// Walk the SDF, collect (entitySlug, rawValue) pairs from any string-typed
// field with `options[]` whose name looks like a status. We scope the
// dictionary tightly so the generated file stays small and predictable.
function _collectStatusValues(sdf) {
  const collected = new Map();
  const entities = Array.isArray(sdf && sdf.entities) ? sdf.entities : [];
  for (const ent of entities) {
    if (!ent || typeof ent !== 'object') continue;
    const slug = typeof ent.slug === 'string' ? ent.slug : null;
    if (!slug) continue;
    const fields = Array.isArray(ent.fields) ? ent.fields : [];
    for (const field of fields) {
      if (!field || typeof field !== 'object') continue;
      const fname = typeof field.name === 'string' ? field.name : '';
      if (!fname) continue;
      // Heuristic: any string field with options[] whose name is `status`
      // (or `*_status`) participates. Other enum fields (e.g. `leave_type`)
      // are intentionally skipped — those aren't workflow states.
      const isStatusField = fname === 'status' || /_status$/.test(fname);
      const options = Array.isArray(field.options) ? field.options : [];
      if (!isStatusField || options.length === 0) continue;
      const set = collected.get(slug) || new Set();
      for (const opt of options) {
        const value = typeof opt === 'string' ? opt : (opt && opt.value);
        if (typeof value === 'string' && value.trim()) set.add(value.trim());
      }
      if (set.size > 0) collected.set(slug, set);
    }
  }
  return collected;
}

/**
 * Build the contents of `src/utils/statusFormatter.ts`.
 *
 * @param {object} options
 * @param {object} options.sdf - The SDF being assembled.
 * @param {string} options.language - Project language (en/tr/...).
 * @returns {string} TypeScript source.
 */
function buildStatusFormatter({ sdf, language } = {}) {
  const lang = normalizeLanguage(language);
  const t = tFor(lang);
  const collected = _collectStatusValues(sdf || {});

  const dict = {};
  for (const [entitySlug, values] of collected.entries()) {
    const entry = {};
    for (const value of values) {
      const valueSlug = slugifyValue(value);
      if (!valueSlug) continue;
      const key = `status.${entitySlug}.${valueSlug}`;
      const translated = t(key);
      // tFor returns the keyPath itself when nothing resolves; treat that as
      // "no translation" and fall back to the raw value at runtime via the
      // formatStatus helper.
      if (translated && translated !== key) {
        entry[value] = translated;
      }
    }
    if (Object.keys(entry).length > 0) {
      dict[entitySlug] = entry;
    }
  }

  const dictJson = JSON.stringify(dict, null, 2);

  return `// AUTO-GENERATED by platform/assembler/generators/frontend/statusFormatter.js
// Do not edit by hand. Regenerate via the assembler.

const STATUS_LABELS: Record<string, Record<string, string>> = ${dictJson};

/**
 * Localize a raw status value (e.g. "Pending", "Approved", "Posted") to the
 * project's language using the dictionary baked in at assembly time. Falls
 * back to the raw value when no translation exists, so adding a new status
 * to an entity does not blank the UI.
 */
export function formatStatus(entitySlug: string, value: unknown): string {
  if (value == null) return '';
  const raw = String(value);
  const perEntity = STATUS_LABELS[entitySlug];
  if (perEntity && Object.prototype.hasOwnProperty.call(perEntity, raw)) {
    return perEntity[raw];
  }
  return raw;
}

export default formatStatus;
`;
}

module.exports = {
  buildStatusFormatter,
  _collectStatusValues,
  slugifyValue,
};
