// Database schema generation - Postgres and SQLite (split from BackendGenerator)
module.exports = {
  _capitalize(str) {
    return str.charAt(0).toUpperCase() + str.slice(1);
  },

  _quoteSqlIdentifier(name) {
    return `"${String(name).replace(/"/g, '""')}"`;
  },

  _toPostgresType(field) {
    if (this._isFieldMultiple(field)) return 'JSONB';

    const type = String(field && field.type ? field.type : 'string').toLowerCase();
    switch (type) {
      case 'integer':
        return 'INTEGER';
      case 'decimal':
        return 'NUMERIC(18,6)';
      case 'number':
        return 'DOUBLE PRECISION';
      case 'boolean':
        return 'BOOLEAN';
      case 'date':
        return 'DATE';
      case 'datetime':
        return 'TIMESTAMPTZ';
      case 'text':
        return 'TEXT';
      case 'reference':
        return 'TEXT';
      case 'string':
      default:
        return 'TEXT';
    }
  },

  _buildDatabaseSchemaSql(entities = []) {
    const allEntities = Array.isArray(entities) ? entities : [];
    const bySlug = new Map();
    for (const entity of allEntities) {
      if (!entity || !entity.slug) continue;
      if (!bySlug.has(entity.slug)) {
        bySlug.set(entity.slug, entity);
      }
    }
    const deferredForeignKeys = [];

    const lines = [
      '-- Generated by CustomERP assembler',
      '-- Database schema for generated ERP entities',
      '',
    ];

    for (const entity of bySlug.values()) {
      const slug = String(entity.slug || '').trim();
      if (!slug) continue;
      const fields = Array.isArray(entity.fields) ? entity.fields : [];
      const table = this._quoteSqlIdentifier(slug);
      const columns = [
        `${this._quoteSqlIdentifier('id')} TEXT PRIMARY KEY`,
        `${this._quoteSqlIdentifier('created_at')} TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
        `${this._quoteSqlIdentifier('updated_at')} TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
      ];

      const seen = new Set(['id', 'created_at', 'updated_at']);
      for (const field of fields) {
        if (!field || !field.name) continue;
        const fieldName = String(field.name);
        if (!fieldName || seen.has(fieldName)) continue;
        seen.add(fieldName);

        const pgType = this._toPostgresType(field);
        const notNull = field.required ? ' NOT NULL' : '';
        const defaultClause = this._isFieldMultiple(field) ? ` DEFAULT '[]'::jsonb` : '';
        columns.push(`${this._quoteSqlIdentifier(fieldName)} ${pgType}${notNull}${defaultClause}`);

        const fieldType = String(field.type || '').toLowerCase();
        const referenceEntity = this._pickFirstString(
          field.reference_entity,
          field.referenceEntity
        );
        if (
          fieldType === 'reference' &&
          referenceEntity &&
          bySlug.has(referenceEntity) &&
          !this._isFieldMultiple(field)
        ) {
          const constraintName = `fk_${slug}_${fieldName}`
            .replace(/[^a-zA-Z0-9_]/g, '_')
            .slice(0, 60);
          deferredForeignKeys.push({
            tableSlug: slug,
            fieldName,
            referenceEntity,
            constraintName,
          });
        }
      }

      lines.push(`CREATE TABLE IF NOT EXISTS ${table} (`);
      lines.push(`  ${columns.join(',\n  ')}`);
      lines.push(');');
      lines.push('');

      for (const field of fields) {
        if (!field || !field.name || !field.unique || this._isFieldMultiple(field)) continue;
        const fieldName = String(field.name);
        if (!fieldName || ['id', 'created_at', 'updated_at'].includes(fieldName)) continue;
        const safeIndexName = `ux_${slug}_${fieldName}`.replace(/[^a-zA-Z0-9_]/g, '_').slice(0, 60);
        lines.push(
          `CREATE UNIQUE INDEX IF NOT EXISTS ${this._quoteSqlIdentifier(safeIndexName)} ON ${table} (${this._quoteSqlIdentifier(fieldName)}) WHERE ${this._quoteSqlIdentifier(fieldName)} IS NOT NULL;`
        );
      }

      const fieldNames = new Set(
        fields
          .map((f) => (f && f.name ? String(f.name) : ''))
          .filter(Boolean)
      );
      const emittedIndexes = new Set();
      const emitIndex = (rawName, columnsSql) => {
        const safe = String(rawName || '')
          .replace(/[^a-zA-Z0-9_]/g, '_')
          .slice(0, 60);
        if (!safe || emittedIndexes.has(safe)) return;
        emittedIndexes.add(safe);
        lines.push(`CREATE INDEX IF NOT EXISTS ${this._quoteSqlIdentifier(safe)} ON ${table} (${columnsSql});`);
      };

      for (const field of fields) {
        if (!field || !field.name || this._isFieldMultiple(field)) continue;
        const fieldName = String(field.name);
        if (!fieldName || ['id', 'created_at', 'updated_at'].includes(fieldName)) continue;
        const fieldType = String(field.type || '').toLowerCase();
        const looksReference = fieldType === 'reference' || fieldName.endsWith('_id');
        const looksStatus = fieldName === 'status';
        const looksNumber = fieldType === 'integer' || fieldType === 'decimal' || fieldType === 'number';

        if (looksReference || looksStatus || looksNumber) {
          emitIndex(`ix_${slug}_${fieldName}`, this._quoteSqlIdentifier(fieldName));
        }
      }

      if (fieldNames.has('status')) {
        for (const fieldName of fieldNames) {
          if (!fieldName.endsWith('_id')) continue;
          const compositeCols = `${this._quoteSqlIdentifier(fieldName)}, ${this._quoteSqlIdentifier('status')}`;
          emitIndex(`ix_${slug}_${fieldName}_status`, compositeCols);
        }
      }
      lines.push('');
    }

    const emittedGlobalIndexes = new Set();
    const emitGlobalIndex = (tableSlug, rawName, columns, unique = false) => {
      const tableEntity = bySlug.get(tableSlug);
      if (!tableEntity) return;
      const fieldNames = new Set(
        (Array.isArray(tableEntity.fields) ? tableEntity.fields : [])
          .map((f) => (f && f.name ? String(f.name) : ''))
          .filter(Boolean)
      );
      const normalizedColumns = (Array.isArray(columns) ? columns : [])
        .map((col) => String(col || '').trim())
        .filter(Boolean);
      if (!normalizedColumns.length) return;
      if (normalizedColumns.some((col) => !fieldNames.has(col))) return;

      const safe = String(rawName || '')
        .replace(/[^a-zA-Z0-9_]/g, '_')
        .slice(0, 60);
      if (!safe || emittedGlobalIndexes.has(safe)) return;
      emittedGlobalIndexes.add(safe);

      const table = this._quoteSqlIdentifier(tableSlug);
      const columnsSql = normalizedColumns.map((col) => this._quoteSqlIdentifier(col)).join(', ');
      if (unique) {
        lines.push(
          `CREATE UNIQUE INDEX IF NOT EXISTS ${this._quoteSqlIdentifier(safe)} ON ${table} (${columnsSql});`
        );
      } else {
        lines.push(`CREATE INDEX IF NOT EXISTS ${this._quoteSqlIdentifier(safe)} ON ${table} (${columnsSql});`);
      }
    };

    const invoiceCfg = this._getInvoicePriorityAConfig();
    if (this._isPackEnabled(invoiceCfg.payments)) {
      emitGlobalIndex(
        invoiceCfg.payments.payment_entity,
        `ix_${invoiceCfg.payments.payment_entity}_${invoiceCfg.payments.payment_date_field}_status`,
        [invoiceCfg.payments.payment_date_field, invoiceCfg.payments.status_field]
      );
      emitGlobalIndex(
        invoiceCfg.payments.allocation_entity,
        `ix_${invoiceCfg.payments.allocation_entity}_${invoiceCfg.payments.allocation_invoice_field}_${invoiceCfg.payments.allocation_payment_field}`,
        [invoiceCfg.payments.allocation_invoice_field, invoiceCfg.payments.allocation_payment_field]
      );
      emitGlobalIndex(
        invoiceCfg.payments.allocation_entity,
        `ix_${invoiceCfg.payments.allocation_entity}_${invoiceCfg.payments.allocation_payment_field}_${invoiceCfg.payments.allocation_invoice_field}`,
        [invoiceCfg.payments.allocation_payment_field, invoiceCfg.payments.allocation_invoice_field]
      );
    }
    if (this._isPackEnabled(invoiceCfg.notes)) {
      emitGlobalIndex(
        invoiceCfg.notes.note_entity,
        `ix_${invoiceCfg.notes.note_entity}_${invoiceCfg.notes.note_type_field}_${invoiceCfg.notes.note_status_field}`,
        [invoiceCfg.notes.note_type_field, invoiceCfg.notes.note_status_field]
      );
    }
    if (this._isPackEnabled(invoiceCfg.transactions)) {
      emitGlobalIndex(
        invoiceCfg.invoiceEntity,
        `ix_${invoiceCfg.invoiceEntity}_${invoiceCfg.statusField}_${invoiceCfg.transactions.posted_at_field}`,
        [invoiceCfg.statusField, invoiceCfg.transactions.posted_at_field]
      );
    }

    const hrCfg = this._getHRPriorityAConfig();
    if (this._isPackEnabled(hrCfg.leaveEngine)) {
      emitGlobalIndex(
        hrCfg.leaveEngine.balance_entity,
        `ux_${hrCfg.leaveEngine.balance_entity}_${hrCfg.leaveEngine.employee_field}_${hrCfg.leaveEngine.leave_type_field}_${hrCfg.leaveEngine.fiscal_year_field}`,
        [
          hrCfg.leaveEngine.employee_field,
          hrCfg.leaveEngine.leave_type_field,
          hrCfg.leaveEngine.fiscal_year_field,
        ],
        true
      );
      emitGlobalIndex(
        hrCfg.leaveEntity,
        `ix_${hrCfg.leaveEntity}_${hrCfg.leaveEngine.employee_field}_${hrCfg.leaveEngine.status_field}_${hrCfg.leaveEngine.start_date_field}`,
        [
          hrCfg.leaveEngine.employee_field,
          hrCfg.leaveEngine.status_field,
          hrCfg.leaveEngine.start_date_field,
        ]
      );
    }
    if (this._isPackEnabled(hrCfg.leaveApprovals)) {
      emitGlobalIndex(
        hrCfg.leaveEntity,
        `ix_${hrCfg.leaveEntity}_${hrCfg.leaveApprovals.status_field}_${hrCfg.leaveApprovals.approver_field}`,
        [hrCfg.leaveApprovals.status_field, hrCfg.leaveApprovals.approver_field]
      );
    }
    if (this._isPackEnabled(hrCfg.attendanceTime)) {
      emitGlobalIndex(
        hrCfg.attendanceTime.attendance_entity,
        `ux_${hrCfg.attendanceTime.attendance_entity}_${hrCfg.attendanceTime.attendance_employee_field}_${hrCfg.attendanceTime.attendance_date_field}`,
        [hrCfg.attendanceTime.attendance_employee_field, hrCfg.attendanceTime.attendance_date_field],
        true
      );
      emitGlobalIndex(
        hrCfg.attendanceTime.timesheet_entity,
        `ux_${hrCfg.attendanceTime.timesheet_entity}_${hrCfg.attendanceTime.timesheet_employee_field}_${hrCfg.attendanceTime.timesheet_date_field}`,
        [hrCfg.attendanceTime.timesheet_employee_field, hrCfg.attendanceTime.timesheet_date_field],
        true
      );
      emitGlobalIndex(
        hrCfg.attendanceTime.shift_entity,
        `ix_${hrCfg.attendanceTime.shift_entity}_${hrCfg.attendanceTime.shift_employee_field}_${hrCfg.attendanceTime.shift_status_field}`,
        [hrCfg.attendanceTime.shift_employee_field, hrCfg.attendanceTime.shift_status_field]
      );
    }
    if (this._isPackEnabled(hrCfg.compensationLedger)) {
      emitGlobalIndex(
        hrCfg.compensationLedger.ledger_entity,
        `ix_${hrCfg.compensationLedger.ledger_entity}_${hrCfg.compensationLedger.ledger_employee_field}_${hrCfg.compensationLedger.ledger_period_field}`,
        [hrCfg.compensationLedger.ledger_employee_field, hrCfg.compensationLedger.ledger_period_field]
      );
      emitGlobalIndex(
        hrCfg.compensationLedger.ledger_entity,
        `ix_${hrCfg.compensationLedger.ledger_entity}_${hrCfg.compensationLedger.ledger_period_field}_${hrCfg.compensationLedger.ledger_status_field}`,
        [hrCfg.compensationLedger.ledger_period_field, hrCfg.compensationLedger.ledger_status_field]
      );
      emitGlobalIndex(
        hrCfg.compensationLedger.snapshot_entity,
        `ux_${hrCfg.compensationLedger.snapshot_entity}_${hrCfg.compensationLedger.snapshot_employee_field}_${hrCfg.compensationLedger.snapshot_period_field}`,
        [hrCfg.compensationLedger.snapshot_employee_field, hrCfg.compensationLedger.snapshot_period_field],
        true
      );
      emitGlobalIndex(
        hrCfg.compensationLedger.snapshot_entity,
        `ix_${hrCfg.compensationLedger.snapshot_entity}_${hrCfg.compensationLedger.snapshot_period_field}_${hrCfg.compensationLedger.snapshot_status_field}`,
        [hrCfg.compensationLedger.snapshot_period_field, hrCfg.compensationLedger.snapshot_status_field]
      );
    }

    if (deferredForeignKeys.length) {
      lines.push('-- Foreign key constraints');
      for (const fk of deferredForeignKeys) {
        const table = this._quoteSqlIdentifier(fk.tableSlug);
        const refTable = this._quoteSqlIdentifier(fk.referenceEntity);
        const field = this._quoteSqlIdentifier(fk.fieldName);
        const constraint = this._quoteSqlIdentifier(fk.constraintName);
        const constraintLiteral = String(fk.constraintName).replace(/'/g, "''");
        lines.push(`DO $$`);
        lines.push(`BEGIN`);
        lines.push(`  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '${constraintLiteral}') THEN`);
        lines.push(`    ALTER TABLE ${table}`);
        lines.push(`      ADD CONSTRAINT ${constraint}`);
        lines.push(`      FOREIGN KEY (${field}) REFERENCES ${refTable} (${this._quoteSqlIdentifier('id')})`);
        lines.push(`      ON UPDATE CASCADE ON DELETE RESTRICT;`);
        lines.push(`  END IF;`);
        lines.push(`END $$;`);
      }
      lines.push('');
    }

    if (lines.length <= 3) {
      lines.push('-- No entities available to generate schema.');
      lines.push('');
    }

    return `${lines.join('\n').trim()}\n`;
  },

  /* ------------------------------------------------------------------
   *  SQLite schema generation (standalone mode)
   * ------------------------------------------------------------------ */

  _toSqliteType(field) {
    if (this._isFieldMultiple(field)) return 'TEXT';
    const type = String(field && field.type ? field.type : 'string').toLowerCase();
    switch (type) {
      case 'integer': return 'INTEGER';
      case 'decimal':
      case 'number': return 'REAL';
      case 'boolean': return 'INTEGER';
      case 'date':
      case 'datetime': return 'TEXT';
      case 'text':
      case 'reference':
      case 'string':
      default: return 'TEXT';
    }
  },

  _buildSQLiteSchemaSql(entities = []) {
    const allEntities = Array.isArray(entities) ? entities : [];
    const bySlug = new Map();
    for (const entity of allEntities) {
      if (!entity || !entity.slug) continue;
      if (!bySlug.has(entity.slug)) bySlug.set(entity.slug, entity);
    }

    const lines = [
      '-- Generated by CustomERP assembler (SQLite)',
      '-- Database schema for generated ERP entities',
      '',
    ];

    for (const entity of bySlug.values()) {
      const slug = String(entity.slug || '').trim();
      if (!slug) continue;
      const fields = Array.isArray(entity.fields) ? entity.fields : [];
      const table = this._quoteSqlIdentifier(slug);
      const columns = [
        `${this._quoteSqlIdentifier('id')} TEXT PRIMARY KEY`,
        `${this._quoteSqlIdentifier('created_at')} TEXT NOT NULL DEFAULT (datetime('now'))`,
        `${this._quoteSqlIdentifier('updated_at')} TEXT NOT NULL DEFAULT (datetime('now'))`,
      ];

      const seen = new Set(['id', 'created_at', 'updated_at']);
      for (const field of fields) {
        if (!field || !field.name) continue;
        const fieldName = String(field.name);
        if (!fieldName || seen.has(fieldName)) continue;
        seen.add(fieldName);

        const sqliteType = this._toSqliteType(field);
        const notNull = field.required ? ' NOT NULL' : '';
        const defaultClause = this._isFieldMultiple(field) ? ` DEFAULT '[]'` : '';

        const fieldType = String(field.type || '').toLowerCase();
        const referenceEntity = this._pickFirstString(field.reference_entity, field.referenceEntity);
        let refClause = '';
        if (
          fieldType === 'reference' &&
          referenceEntity &&
          bySlug.has(referenceEntity) &&
          !this._isFieldMultiple(field)
        ) {
          refClause = ` REFERENCES ${this._quoteSqlIdentifier(referenceEntity)}(${this._quoteSqlIdentifier('id')}) ON UPDATE CASCADE ON DELETE RESTRICT`;
        }

        columns.push(`${this._quoteSqlIdentifier(fieldName)} ${sqliteType}${notNull}${defaultClause}${refClause}`);
      }

      lines.push(`CREATE TABLE IF NOT EXISTS ${table} (`);
      lines.push(`  ${columns.join(',\n  ')}`);
      lines.push(');');
      lines.push('');

      for (const field of fields) {
        if (!field || !field.name || !field.unique || this._isFieldMultiple(field)) continue;
        const fieldName = String(field.name);
        if (!fieldName || ['id', 'created_at', 'updated_at'].includes(fieldName)) continue;
        const safeIndexName = `ux_${slug}_${fieldName}`.replace(/[^a-zA-Z0-9_]/g, '_').slice(0, 60);
        lines.push(
          `CREATE UNIQUE INDEX IF NOT EXISTS ${this._quoteSqlIdentifier(safeIndexName)} ON ${table} (${this._quoteSqlIdentifier(fieldName)}) WHERE ${this._quoteSqlIdentifier(fieldName)} IS NOT NULL;`
        );
      }

      const fieldNames = new Set(fields.map((f) => (f && f.name ? String(f.name) : '')).filter(Boolean));
      const emittedIndexes = new Set();
      const emitIndex = (rawName, columnsSql) => {
        const safe = String(rawName || '').replace(/[^a-zA-Z0-9_]/g, '_').slice(0, 60);
        if (!safe || emittedIndexes.has(safe)) return;
        emittedIndexes.add(safe);
        lines.push(`CREATE INDEX IF NOT EXISTS ${this._quoteSqlIdentifier(safe)} ON ${table} (${columnsSql});`);
      };

      for (const field of fields) {
        if (!field || !field.name || this._isFieldMultiple(field)) continue;
        const fieldName = String(field.name);
        if (!fieldName || ['id', 'created_at', 'updated_at'].includes(fieldName)) continue;
        const fieldType = String(field.type || '').toLowerCase();
        const looksReference = fieldType === 'reference' || fieldName.endsWith('_id');
        const looksStatus = fieldName === 'status';
        const looksNumber = fieldType === 'integer' || fieldType === 'decimal' || fieldType === 'number';
        if (looksReference || looksStatus || looksNumber) {
          emitIndex(`ix_${slug}_${fieldName}`, this._quoteSqlIdentifier(fieldName));
        }
      }

      if (fieldNames.has('status')) {
        for (const fieldName of fieldNames) {
          if (!fieldName.endsWith('_id')) continue;
          const compositeCols = `${this._quoteSqlIdentifier(fieldName)}, ${this._quoteSqlIdentifier('status')}`;
          emitIndex(`ix_${slug}_${fieldName}_status`, compositeCols);
        }
      }
      lines.push('');
    }

    if (lines.length <= 3) {
      lines.push('-- No entities available to generate schema.');
      lines.push('');
    }

    return `${lines.join('\n').trim()}\n`;
  },
};
